### ISSUE TITLE
[1.18] Debug message printing in console

### ISSUE THREAD

**Issue by kwpugh** [MalekiRe/MaleksBlink#1]
Hello, very nicely down mod.

I'm getting some debug message from your mod in my console.  No biggie, but I thought I would let you know.  Looks like they are coming from you Hud mixin.

![Screen Shot 2021-10-22 at 7 53 52 PM](https://user-images.githubusercontent.com/8809210/138536177-a9a03ad6-e040-4e19-b76a-62a9de690667.png)
e.

regards.

P.S. I forget those all the time in my mods.

**Comment by MalekiRe** [comment]
Oh my gosh thank you!

**Comment by kwpugh** [comment]
Tried the new release, still have some messages
<img width="447" alt="Screen Shot 2021-10-23 at 7 03 30 AM" src="https://user-images.githubusercontent.com/8809210/138555306-4daa8a04-e4dc-4bf4-939e-ef15843f0294.png">
:

Also, the file name version is still 1.0.0.  You need to update here
<img width="623" alt="Screen Shot 2021-10-23 at 7 04 13 AM" src="https://user-images.githubusercontent.com/8809210/138555329-f7055019-6e80-4d27-8e6b-ef8be444e3cc.png">
